### ISSUE TITLE
Hit Detection

### ISSUE THREAD

**Issue by kelcecil** [abutcher/FortSiege#4]
Need to get hit detection in place between the GameObjects and the map. Characters should move freely until confronted with something they should act on (See AI)

**Comment by jimethn** [comment]
GameObject now has 3 new methods:
- getCollision - returns the first object that this object is touching
- collideWith - called during a collision, passing the touched object

If updateObject detects a collision, it calls the collideWith method on both involved objects (passing the other actor), allowing both objects to have their own behavior whenever a collision occurs.

Might need fixed up more still, because there's a possibility if you are touching multiple things that you will change targets every cycle.
